#!/bin/bash
SHELL=/bin/bash -l 
#
##---global
#47 2,8,14,20 * * * jtyp=gfs cyc=`date --date="-2 hours" +\%H` PDY=`date +\%Y\%m\%d` desc=GlobalTacV1.1.1 bash  /u/nicholas.esposito/bin/cycqsub /lfs/h2/emc/obsproc/noscrub/nicholas.esposito/TAC/triggers/jglobal_dump.wc2.pbs > /dev/null 2>&1
#50 5,11,17,23 * * * jtyp=gdas cyc=`date --date="-5 hours" +\%H` PDY=`date +\%Y\%m\%d` desc=GlobalTacV1.1.1 bash  /u/nicholas.esposito/bin/cycqsub /lfs/h2/emc/obsproc/noscrub/nicholas.esposito/TAC/triggers/jglobal_dump.wc2.pbs > /dev/null 2>&1

##---rap
######SHELLEYS CRON BUT DOESN"T APPEAR TO CHANGE. RETRIEVED 20230323
#00 7,19 * * * jtyp=rap_p cyc=`date --date="-4 hours" +\%H` PDY=`date +\%Y\%m\%d` desc=RapTacV1.1.1 /u/nicholas.esposito/bin/cycqsub /lfs/h2/emc/obsproc/noscrub/nicholas.esposito/triggers/jrap_dump.wc2.pbs > /dev/null 2>&1
#00 7,8,19,20 * * * jtyp=rap_p cyc=`date --date="-3 hours" +\%H` PDY=`date +\%Y\%m\%d` desc=RapTacV1.1.1 /u/nicholas.esposito/bin/cycqsub /lfs/h2/emc/obsproc/noscrub/nicholas.esposito/triggers/jrap_dump.wc2.pbs > /dev/null 2>&1
#00 8,9,20,21 * * * jtyp=rap_p cyc=`date --date="-2 hours" +\%H` PDY=`date +\%Y\%m\%d` desc=RapTacV1.1.1 /u/nicholas.esposito/bin/cycqsub /lfs/h2/emc/obsproc/noscrub/nicholas.esposito/triggers/jrap_dump.wc2.pbs > /dev/null 2>&1
#00 9,21 * * * jtyp=rap_p cyc=`date --date="-1 hours" +\%H` PDY=`date +\%Y\%m\%d` desc=RapTacV1.1.1 /u/nicholas.esposito/bin/cycqsub /lfs/h2/emc/obsproc/noscrub/nicholas.esposito/triggers/jrap_dump.wc2.pbs > /dev/null 2>&1
#---
#26 0,12 * * * jtyp=rap_e cyc=`date +\%H` PDY=`date +\%Y\%m\%d` desc=RapTacV1.1.1 /u/nicholas.esposito/bin/cycqsub /lfs/h2/emc/obsproc/noscrub/nicholas.esposito/triggers/jrap_dump.wc2.pbs > /dev/null 2>&1
##---
#26 1-11 * * * jtyp=rap cyc=`date +\%H` PDY=`date +\%Y\%m\%d` desc=RapTacV1.1.1 bash  /u/nicholas.esposito/bin/cycqsub /lfs/h2/emc/obsproc/noscrub/nicholas.esposito/TAC/triggers/jrap_dump.wc2.pbs > /dev/null 2>&1
#26 13-23 * * * jtyp=rap cyc=`date +\%H` PDY=`date +\%Y\%m\%d` desc=RapTacV1.1.1 bash  /u/nicholas.esposito/bin/cycqsub /lfs/h2/emc/obsproc/noscrub/nicholas.esposito/TAC/triggers/jrap_dump.wc2.pbs > /dev/null 2>&1
#58 0,12 * * * jtyp=rap cyc=`date +\%H` PDY=`date +\%Y\%m\%d` desc=RapTacV1.1.1 bash  /u/nicholas.esposito/bin/cycqsub /lfs/h2/emc/obsproc/noscrub/nicholas.esposito/TAC/triggers/jrap_dump.wc2.pbs > /dev/null 2>&1
###############





################################
##--rap and global test whenever you want #MAKE SURE BOTH ARE COMMENTED WHEN DONE WITH THEM
#06 16 * * * jtyp=rap cyc=`date +\%H` PDY=`date +\%Y\%m\%d` desc=RapTacV1.1.1 bash  /u/nicholas.esposito/bin/cycqsub /lfs/h2/emc/obsproc/noscrub/nicholas.esposito/TAC/triggers/jrap_dump.wc2.pbs > /dev/null 2>&1
#06 16 * * * jtyp=gfs cyc=`date --date="-16 hours" +\%H` PDY=`date +\%Y\%m\%d` desc=GlobalTAC bash  /u/nicholas.esposito/bin/cycqsub /lfs/h2/emc/obsproc/noscrub/nicholas.esposito/TAC/triggers/jglobal_dump.wc2.pbs > /dev/null 2>&1
#38 16 * * * jtyp=gdas cyc=`date --date="-16 hours" +\%H` PDY=`date +\%Y\%m\%d` desc=GlobalTAC bash  /u/nicholas.esposito/bin/cycqsub /lfs/h2/emc/obsproc/noscrub/nicholas.esposito/TAC/triggers/jglobal_dump.wc2.pbs > /dev/null 2>&1
################################
##prep
#09 15 * * * jtyp=gfs cyc=`date --date="-15 hours" +\%H` PDY=`date +\%Y\%m\%d` desc=GlobalTAC bash  /u/nicholas.esposito/bin/cycqsub /lfs/h2/emc/obsproc/noscrub/nicholas.esposito/TAC/triggers/jglobal_prep.wc2.pbs.NEW > /dev/null 2>&1
##### Old stuff
#30 * * * *  /bin/bash  /lfs/h2/emc/obsproc/noscrub/nicholas.esposito/cron_project/jdump_monitor.wc2.sge > /u/nicholas.esposito/trial 2>&1
#30 * * * * jtyp=dump_monitor cyc=12 PDY=20210824 desc=wc2 bash  /u/nicholas.esposito/bin/cycqsub /lfs/h2/emc/obsproc/noscrub/nicholas.esposito/cron_project/jdump_monitor.wc2.pbs > /u/nicholas.esposito/trial 2>&1
